[files]
defaultdir = 'd:\onedrive\_2023'
excludedirs = [ "m101_edu", "ngc6888-mosaic", "sn2023ixf", "various" ]

#extr = "Optolong L-eXtreme"
#lpro = "Optolong L-Pro"
#haoiii=Altair Ha Oii (4nm)

[telescopes]
list = [ "esprit", "edgehd" ]

[esprit]
name = "Skywatcher Esprit 100ED"
synonyms = [ "skywatcher esprit 10" ]

[edgehd]
name = "Celestron EdgeHD 925"

########## filters ####################
[filters]
list = [ "lextreme", "lpro", "uvir", "haoiii"]

[lextreme]
name = "Optolong L-eXtreme"
synonyms = [ "extr" ]

[lpro]
name = "Optolong L-Pro"
synonyms = [ "lpro" ]

[uvir]
name = "Optolong UV/IR"
synonyms = [ "uvir" ]

[haoiii]
name = "Altair Ha Oii 4nm" 
synonyms = [ "haoiii" ]